import React from "react";
import Main from "../template/Main";

export default props =>
    <Main icon="Home" title="Inicio"
        subtitle="Segundo Projeto do capítulo React">
        <div className='display-4'>Seja Bem Vindo!</div>
        <p className='mb-0'><p>Lorem ipsum dolor sit amet. Eum facilis suscipit 33 deleniti assumenda 33 quis repellendus. Non numquam inventore ut repudiandae nostrum sed animi quidem et dolore tempora eum sunt repudiandae. </p><p>Non eius perferendis aut quia impedit ut deserunt ratione sed asperiores inventore. Aut commodi labore ea eius ipsa vel accusamus doloremque eum officia quaerat est exercitationem voluptatem. Rem assumenda recusandae non voluptas voluptatem qui labore molestiae ut aperiam obcaecati et libero dolore aut expedita rerum qui placeat mollitia. Est odit  ad fugiat animi et voluptas alias in unde Quis sit voluptatem nisi. </p><p>Aut nihil corrupti ex amet asperiores est tenetur natus sed temporibus quia. Vel unde provident et delectus tenetur ut doloremque voluptas ut quos porro. </p><p>Ut cumque voluptas qui unde accusamus sed voluptatem neque. Est repellat qui optio rerum qui rerum consequuntur qui nesciunt consequatur. Aut dolorem rerum ut sint eligendi qui earum fugiat.</p><p>Lorem ipsum dolor sit amet. Sed quos quia ut voluptatem accusantium est pariatur unde vel mollitia maiores ad numquam eaque et excepturi illum. Et perferendis quae est rerum sint ut laudantium magni a earum velit quo voluptatem quaerat. </p><p>Non amet corporis aut velit dolorum est laborum dolorum. Hic dolores reprehenderit aut doloremque eligendi et ipsam optio. Non quod ipsa nam rerum unde non praesentium veniam. Ea Quis cumque aut suscipit quaerat sit quidem excepturi At minus nulla aut repudiandae modi cum corrupti voluptas.</p>
</p>
    </Main>